name: Autograde Solidity Assignment

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install --global ganache
        npm install -g truffle

    - name: Autograding
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Autograding
        command: truffle test